name: mycondaenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.3
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.4
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - appnope==0.1.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - cma==4.0.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cryptography==43.0.1
      - cycler==0.12.1
      - cython==3.0.11
      - debugpy==1.8.5
      - decorator==5.1.1
      - dill==0.3.8
      - executing==2.1.0
      - fonttools==4.53.1
      - gpy==1.13.2
      - h5py==3.11.0
      - hypermapper==2.2.13
      - ibm-cloud-sdk-core==3.20.6
      - ibm-platform-services==0.57.0
      - idna==3.8
      - ipykernel==6.29.5
      - ipython==8.27.0
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.2
      - paramz==0.9.6
      - parso==0.8.4
      - patsy==0.5.6
      - pbr==6.1.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.1
      - ply==3.11
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-bobyqa==1.4.1
      - pycparser==2.22
      - pydantic==2.9.0
      - pydantic-core==2.23.2
      - pydoe==0.3.8
      - pygments==2.18.0
      - pyjwt==2.9.0
      - pyparsing==3.1.4
      - pyscf==2.6.2
      - pyspnego==0.11.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyzmq==26.2.0
      - qiskit==1.2.0
      - qiskit-aer==0.15.0
      - qiskit-algorithms==0.3.0
      - qiskit-ibm-runtime==0.29.0
      - qiskit-nature==0.7.2
      - referencing==0.35.1
      - requests==2.32.3
      - requests-ntlm==1.3.0
      - rpds-py==0.20.0
      - rustworkx==0.15.1
      - scikit-learn==1.5.1
      - scikit-quant==0.8.2
      - scipy==1.12.0
      - six==1.16.0
      - sqcommon==0.3.2
      - sqimfil==0.3.7
      - sqsnobfit==0.4.5
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stevedore==5.3.0
      - stim==1.13.0
      - symengine==0.11.0
      - sympy==1.13.2
      - threadpoolctl==3.5.0
      - tornado==6.4.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - websocket-client==1.8.0
